### ISSUE TITLE
Latest version of Bleam doesn't start

### ISSUE THREAD

**Issue by ElPumpo** [no1dead/Bleam#1]
Seems like you left an error, trying to get a `ClickState` from a `Button` doesn't work. My fork have fixed this serious bug.

**Comment by n1-d** [comment]
Do a pull request?

**Comment by n1-d** [comment]
I've also checked this version on multiple copies of windows. It's working perfectly fine.

**Comment by ElPumpo** [comment]
What version of VS are you using, I'm using VS2015 Update 3
What version of Windows have you been testing Bleam on, I've tested it on Windows 10 14393.693

> Tillämpningsprogram: Bleam.exe
Framework-version: v4.0.30319
Beskrivning: Processen avslutades på grund av ett ohanterat undantag.
Undantagsinformation: System.NullReferenceException
   vid Bleam.hForm.Auto_FOV_CheckedChanged()
   vid Bleam.hForm..ctor()
   vid Bleam.Program.Main()

`bool fov_auto = System.Convert.ToBoolean(Auto_FOV_CheckedChanged()); `

What version of Bleam have you been trying, v1.0.1.10 is the one that doesn't work, the previous version works fine. It's obviously something from your side, because you simply cannot 

Not only that, but what's up with the internal code? Duplicate class files and the very inapproiate language...

**Comment by n1-d** [comment]
That's previously unfinished code I had never got it working in the first place. The internal language, and duplicate files are things I'm just not gonna be bother to fixing all my commits are like this.

**Comment by ElPumpo** [comment]
`Commented out because I triggered someone` - e10d25c6cb568fbd50073e8dcba7900056491a93

![explain](https://cloud.githubusercontent.com/assets/12564301/23588029/2104967a-01b7-11e7-8776-f3baa364b56f.png)
That's tree 2fc4e1198f0fb35c4402afd549dba94cc6522948 - the version I spoke about when started this issue

You're very inmature take conclusions way too quick, nice helping you out.. **bye**
